version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: eslint-presets/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: packages/stylelint-paintbrush/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

    - package-ecosystem: npm
  directory: packages/stylelint-scss/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: packages/stylelint-standard/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: packages/stylelint-vue/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: npm
  directory: packages/stylelint-vue-scss/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"

- package-ecosystem: pip
  directory: packages/yamllint-standard/
  schedule:
    interval: weekly
  commit-message:
    prefix: ":paperclip:"
