packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false

overrides:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.8.tsgo.7.0.2

peerDependencyRules:
  allowedVersions:
    stylelint: ^17.0.0
    eslint: ^10.0.0
