module.exports = {
  extends: [ 'stylelint-config-recommended' ],
  ignoreFiles: [ 'node_modules/**' ],
  plugins: [ 'stylelint-order', 'stylelint-high-performance-animation', '@danifoldi/stylelint-presets/standard/no-future-comment.js' ],
  rules: {
    'at-rule-name-case': 'lower',
    'at-rule-name-space-after': 'always-single-line',
    'at-rule-no-unknown': true,
    'at-rule-semicolon-newline-after': 'always',
    'block-closing-brace-empty-line-before': 'never',
    'block-closing-brace-newline-after': [ 'always', { ignoreAtRules: [ 'if', 'else' ] }],
    'block-closing-brace-newline-before': 'always',
    'block-no-empty': true,
    'block-opening-brace-space-before': 'always',
    'color-hex-case': 'lower',
    'custom/no-future-comment': [ true, { disallow: [ 'todo', 'fixme' ], severity: 'warning' }],
    'declaration-block-semicolon-newline-after': 'always',
    'declaration-block-semicolon-newline-before': 'never-multi-line',
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-no-important': true,
    'function-name-case': 'lower',
    'function-no-unknown': true,
    'indentation': [ 2, { baseIndentLevel: 1 }],
    'length-zero-no-unit': true,
    'max-empty-lines': 2,
    'max-line-length': 120,
    'max-nesting-depth': 5,
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-case': 'lower',
    'media-feature-parentheses-space-inside': 'never',
    'media-query-list-comma-newline-after': 'never-multi-line',
    'media-query-list-comma-newline-before': 'never-multi-line',
    'media-query-list-comma-space-after': 'always',
    'media-query-list-comma-space-before': 'never',
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-first-line': true,
    'no-empty-source': [ true, { severity: 'warning' }],
    'no-eol-whitespace': true,
    'no-extra-semicolons': true,
    'no-missing-end-of-source-newline': true,
    'number-leading-zero': 'never',
    'order/order': [ 'custom-properties', 'declarations', 'at-rules', 'rules' ],
    'order/properties-alphabetical-order': true,
    'plugin/no-low-performance-animation-properties': [ true, { ignore: 'paint-properties' }],
    'property-no-unknown': true,
    'rule-empty-line-before': [ 'always', { except: [ 'after-single-line-comment' ] }],
    'selector-attribute-brackets-space-inside': 'never',
    'selector-attribute-operator-space-after': 'never',
    'selector-attribute-operator-space-before': 'never',
    'selector-attribute-quotes': 'never',
    'selector-combinator-space-before': 'always',
    'selector-id-pattern': '^(__)?[a-zA-Z]+(-[a-zA-Z0-9]+)*$',
    'selector-list-comma-newline-after': 'always-multi-line',
    'selector-list-comma-newline-before': 'never-multi-line',
    'selector-list-comma-space-after': 'always-single-line',
    'selector-list-comma-space-before': 'never',
    'selector-pseudo-element-no-unknown': true,
    'selector-type-case': 'lower',
    'shorthand-property-no-redundant-values': [ true, { severity: 'warning' }],
    'string-quotes': 'single',
    'unit-no-unknown': true,
    'value-keyword-case': 'lower'
  }
}
