name: ESLint

defaults:
  run:
    working-directory: eslint-presets

on: # yamllint disable-line rule:truthy
  push:
    branches:
    - main
    paths:
    - 'eslint-presets/**'
  pull_request:
    branches:
    - main
    paths:
    - 'eslint-presets/**'
    types:
    - opened
    - synchronize

jobs:
  lint-linters:
    name: Lint the linters repository
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: |
        npm ci --no-progress

    - name: Run lint script
      run: |
        npm run lint

  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: contains( join( github.event.commits.*.message, ', ' ), '[ci release]' )

    needs:
    - lint-linters

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: 'eslint-presets/**/package.json'

    - uses: JS-DevTools/npm-publish@v1
      with:
        access: public
        package: eslint-presets/package.json
        token: ${{ secrets.NPM_TOKEN }}
